//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.235
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatWalk.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CatWalk.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Add... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CollectionEditDialog_AddButton {
            get {
                return ResourceManager.GetString("CollectionEditDialog_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CollectionEditDialog_EditButton {
            get {
                return ResourceManager.GetString("CollectionEditDialog_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move _Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CollectionEditDialog_MoveDownButton {
            get {
                return ResourceManager.GetString("CollectionEditDialog_MoveDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move _Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CollectionEditDialog_MoveUpButton {
            get {
                return ResourceManager.GetString("CollectionEditDialog_MoveUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CollectionEditDialog_RemoveButton {
            get {
                return ResourceManager.GetString("CollectionEditDialog_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bold に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontDialog_BoldCheckBox {
            get {
                return ResourceManager.GetString("FontDialog_BoldCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontDialog_FontLabel {
            get {
                return ResourceManager.GetString("FontDialog_FontLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Langugage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontDialog_LanguageLabel {
            get {
                return ResourceManager.GetString("FontDialog_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sa_mple に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontDialog_SampleLabel {
            get {
                return ResourceManager.GetString("FontDialog_SampleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontDialog_SizeLabel {
            get {
                return ResourceManager.GetString("FontDialog_SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontDialog_Title {
            get {
                return ResourceManager.GetString("FontDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T_ype Face に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FontDialog_TypeFaceLabel {
            get {
                return ResourceManager.GetString("FontDialog_TypeFaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
    }
}
