//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekome.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nekome.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Argument: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_ArgumentLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_ArgumentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Column Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_ColumnNumberMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_ColumnNumberMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_DirectoryMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_DirectoryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EmEdi_tor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_EmEditorMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_EmEditorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Escaped _File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_EscapedFilePathMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_EscapedFilePathMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_scape に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_EscapeMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_EscapeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_ExtensionMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_ExtensionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File _Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_FileNameLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_FileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File _Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_FileNameMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_FileNameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Na_me Without Extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_FileNameWithoutExtensionMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_FileNameWithoutExtensionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File _Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_FilePathMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_FilePathMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Hidemaru に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_HidemaruMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_HidemaruMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Hotkey: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_HotkeyLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_HotkeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Line Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_LineNumberMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_LineNumberMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logical C_olumn Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_LogicalColumnNumberMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_LogicalColumnNumberMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logical L_ine Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_LogicalLineNumberMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_LogicalLineNumberMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_NameLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_OpenButton {
            get {
                return ResourceManager.GetString("ExternalToolForm_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replacement Macro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_ReplacementMacroButton {
            get {
                return ResourceManager.GetString("ExternalToolForm_ReplacementMacroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_Title {
            get {
                return ResourceManager.GetString("ExternalToolForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Verb: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_VerbLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_VerbLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window _Style; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_WindowStyleLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_WindowStyleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Working Directory: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalToolForm_WorkingDirectoryLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_WorkingDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Faild to check updates.\n{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FaildToCheckUpdates {
            get {
                return ResourceManager.GetString("FaildToCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Faild to download the installer.\n{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FaildToDownloadInstaller {
            get {
                return ResourceManager.GetString("FaildToDownloadInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FindResultView_DeleteMenu {
            get {
                return ResourceManager.GetString("FindResultView_DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FindResultView_PathColumn {
            get {
                return ResourceManager.GetString("FindResultView_PathColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version {0} is found. Do you install this? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FoundUpdateDialog {
            get {
                return ResourceManager.GetString("FoundUpdateDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GrepResultView_ColumnColumn {
            get {
                return ResourceManager.GetString("GrepResultView_ColumnColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GrepResultView_DeleteMenu {
            get {
                return ResourceManager.GetString("GrepResultView_DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encoding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GrepResultView_EncodingColumn {
            get {
                return ResourceManager.GetString("GrepResultView_EncodingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GrepResultView_LineColumn {
            get {
                return ResourceManager.GetString("GrepResultView_LineColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GrepResultView_PathColumn {
            get {
                return ResourceManager.GetString("GrepResultView_PathColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GrepResultView_PreviewColumn {
            get {
                return ResourceManager.GetString("GrepResultView_PreviewColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Abort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_AbortMenu {
            get {
                return ResourceManager.GetString("MainForm_AbortMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_AboutMenu {
            get {
                return ResourceManager.GetString("MainForm_AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Check Updates... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_CheckUpdateMenu {
            get {
                return ResourceManager.GetString("MainForm_CheckUpdateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check _Updates On Start Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_CheckUpdateOnStartUpMenu {
            get {
                return ResourceManager.GetString("MainForm_CheckUpdateOnStartUpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close Tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_CloseTabMenu {
            get {
                return ResourceManager.GetString("MainForm_CloseTabMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Find Tools... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_EditFindToolsButton {
            get {
                return ResourceManager.GetString("MainForm_EditFindToolsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit _Search Tools... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_EditFindToolsMenu {
            get {
                return ResourceManager.GetString("MainForm_EditFindToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Grep Tools... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_EditGrepToolsButton {
            get {
                return ResourceManager.GetString("MainForm_EditGrepToolsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit _Grep Tools... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_EditGrepToolsMenu {
            get {
                return ResourceManager.GetString("MainForm_EditGrepToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_EditToolsTitle {
            get {
                return ResourceManager.GetString("MainForm_EditToolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_ExitMenu {
            get {
                return ResourceManager.GetString("MainForm_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_FileMenu {
            get {
                return ResourceManager.GetString("MainForm_FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Search is canceled [Elapsed {0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_FileSearchCanceledMessage {
            get {
                return ResourceManager.GetString("MainForm_FileSearchCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Search is complete [Elapsed {0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_FileSearchCompleteMessage {
            get {
                return ResourceManager.GetString("MainForm_FileSearchCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Searching [Elapsed {0}]: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_FileSearchingMessage {
            get {
                return ResourceManager.GetString("MainForm_FileSearchingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grep is canceled [Elapsed {0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_GrepCanceledMessage {
            get {
                return ResourceManager.GetString("MainForm_GrepCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grep is complete [Elapsed {0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_GrepCompleteMessage {
            get {
                return ResourceManager.GetString("MainForm_GrepCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grepping [Elapsed {0}]: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_GreppingMessage {
            get {
                return ResourceManager.GetString("MainForm_GreppingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_HelpMenu {
            get {
                return ResourceManager.GetString("MainForm_HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search (Ctrl+F)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_SearchButton {
            get {
                return ResourceManager.GetString("MainForm_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_SearchMenu {
            get {
                return ResourceManager.GetString("MainForm_SearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Search... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_SearchSearchMenu {
            get {
                return ResourceManager.GetString("MainForm_SearchSearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set _Grep Preview Font... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_SetGrepPreviewFont {
            get {
                return ResourceManager.GetString("MainForm_SetGrepPreviewFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_ViewMenu {
            get {
                return ResourceManager.GetString("MainForm_ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainForm_WindowMenu {
            get {
                return ResourceManager.GetString("MainForm_WindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No updates are available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Advanced に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_Advanced {
            get {
                return ResourceManager.GetString("SearchForm_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Directory: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_Directory {
            get {
                return ResourceManager.GetString("SearchForm_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Excluding File Masks: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_ExcludingFileMask {
            get {
                return ResourceManager.GetString("SearchForm_ExcludingFileMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Targets: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_ExcludingTargets {
            get {
                return ResourceManager.GetString("SearchForm_ExcludingTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File _Masks: Can be used multiple file masks by seperating with &apos;;&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_FileMask {
            get {
                return ResourceManager.GetString("SearchForm_FileMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Si_ze Range: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_FileSizeRange {
            get {
                return ResourceManager.GetString("SearchForm_FileSizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Ignore Case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_IgnoreCase {
            get {
                return ResourceManager.GetString("SearchForm_IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Include _Subdirectories に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_IncludeSubdirectories {
            get {
                return ResourceManager.GetString("SearchForm_IncludeSubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_Max {
            get {
                return ResourceManager.GetString("SearchForm_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_Min {
            get {
                return ResourceManager.GetString("SearchForm_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_Open {
            get {
                return ResourceManager.GetString("SearchForm_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Regular Expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_RegularExpression {
            get {
                return ResourceManager.GetString("SearchForm_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search _Word: Find files when empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_SearchWord {
            get {
                return ResourceManager.GetString("SearchForm_SearchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Conditions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchForm_Title {
            get {
                return ResourceManager.GetString("SearchForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
    }
}
