//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekome.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nekome.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Argument:.
        /// </summary>
        public static string ExternalToolForm_ArgumentLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_ArgumentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Column Number.
        /// </summary>
        public static string ExternalToolForm_ColumnNumberMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_ColumnNumberMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Directory.
        /// </summary>
        public static string ExternalToolForm_DirectoryMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_DirectoryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmEdi_tor.
        /// </summary>
        public static string ExternalToolForm_EmEditorMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_EmEditorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escaped _File Path.
        /// </summary>
        public static string ExternalToolForm_EscapedFilePathMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_EscapedFilePathMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_scape.
        /// </summary>
        public static string ExternalToolForm_EscapeMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_EscapeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Extension.
        /// </summary>
        public static string ExternalToolForm_ExtensionMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_ExtensionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File _Name:.
        /// </summary>
        public static string ExternalToolForm_FileNameLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_FileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File _Name.
        /// </summary>
        public static string ExternalToolForm_FileNameMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_FileNameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Na_me Without Extension.
        /// </summary>
        public static string ExternalToolForm_FileNameWithoutExtensionMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_FileNameWithoutExtensionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File _Path.
        /// </summary>
        public static string ExternalToolForm_FilePathMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_FilePathMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hidemaru.
        /// </summary>
        public static string ExternalToolForm_HidemaruMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_HidemaruMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hotkey:.
        /// </summary>
        public static string ExternalToolForm_HotkeyLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_HotkeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Line Number.
        /// </summary>
        public static string ExternalToolForm_LineNumberMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_LineNumberMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical C_olumn Number.
        /// </summary>
        public static string ExternalToolForm_LogicalColumnNumberMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_LogicalColumnNumberMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical L_ine Number.
        /// </summary>
        public static string ExternalToolForm_LogicalLineNumberMenu {
            get {
                return ResourceManager.GetString("ExternalToolForm_LogicalLineNumberMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string ExternalToolForm_NameLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string ExternalToolForm_OpenButton {
            get {
                return ResourceManager.GetString("ExternalToolForm_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Macro.
        /// </summary>
        public static string ExternalToolForm_ReplacementMacroButton {
            get {
                return ResourceManager.GetString("ExternalToolForm_ReplacementMacroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tools.
        /// </summary>
        public static string ExternalToolForm_Title {
            get {
                return ResourceManager.GetString("ExternalToolForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Verb:.
        /// </summary>
        public static string ExternalToolForm_VerbLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_VerbLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window _Style;.
        /// </summary>
        public static string ExternalToolForm_WindowStyleLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_WindowStyleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Working Directory:.
        /// </summary>
        public static string ExternalToolForm_WorkingDirectoryLabel {
            get {
                return ResourceManager.GetString("ExternalToolForm_WorkingDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild to check updates.\n{0}.
        /// </summary>
        public static string FaildToCheckUpdates {
            get {
                return ResourceManager.GetString("FaildToCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild to download the installer.\n{0}.
        /// </summary>
        public static string FaildToDownloadInstaller {
            get {
                return ResourceManager.GetString("FaildToDownloadInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string FindResultView_DeleteMenu {
            get {
                return ResourceManager.GetString("FindResultView_DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string FindResultView_PathColumn {
            get {
                return ResourceManager.GetString("FindResultView_PathColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is found. Do you install this?.
        /// </summary>
        public static string FoundUpdateDialog {
            get {
                return ResourceManager.GetString("FoundUpdateDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string GrepResultView_ColumnColumn {
            get {
                return ResourceManager.GetString("GrepResultView_ColumnColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string GrepResultView_DeleteMenu {
            get {
                return ResourceManager.GetString("GrepResultView_DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string GrepResultView_EncodingColumn {
            get {
                return ResourceManager.GetString("GrepResultView_EncodingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string GrepResultView_LineColumn {
            get {
                return ResourceManager.GetString("GrepResultView_LineColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string GrepResultView_PathColumn {
            get {
                return ResourceManager.GetString("GrepResultView_PathColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string GrepResultView_PreviewColumn {
            get {
                return ResourceManager.GetString("GrepResultView_PreviewColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Abort.
        /// </summary>
        public static string MainForm_AbortMenu {
            get {
                return ResourceManager.GetString("MainForm_AbortMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string MainForm_AboutMenu {
            get {
                return ResourceManager.GetString("MainForm_AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Check Updates....
        /// </summary>
        public static string MainForm_CheckUpdateMenu {
            get {
                return ResourceManager.GetString("MainForm_CheckUpdateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check _Updates On Start Up.
        /// </summary>
        public static string MainForm_CheckUpdateOnStartUpMenu {
            get {
                return ResourceManager.GetString("MainForm_CheckUpdateOnStartUpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close Tab.
        /// </summary>
        public static string MainForm_CloseTabMenu {
            get {
                return ResourceManager.GetString("MainForm_CloseTabMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Find Tools....
        /// </summary>
        public static string MainForm_EditFindToolsButton {
            get {
                return ResourceManager.GetString("MainForm_EditFindToolsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit _Search Tools....
        /// </summary>
        public static string MainForm_EditFindToolsMenu {
            get {
                return ResourceManager.GetString("MainForm_EditFindToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Grep Tools....
        /// </summary>
        public static string MainForm_EditGrepToolsButton {
            get {
                return ResourceManager.GetString("MainForm_EditGrepToolsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit _Grep Tools....
        /// </summary>
        public static string MainForm_EditGrepToolsMenu {
            get {
                return ResourceManager.GetString("MainForm_EditGrepToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tools.
        /// </summary>
        public static string MainForm_EditToolsTitle {
            get {
                return ResourceManager.GetString("MainForm_EditToolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MainForm_ExitMenu {
            get {
                return ResourceManager.GetString("MainForm_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainForm_FileMenu {
            get {
                return ResourceManager.GetString("MainForm_FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MainForm_HelpMenu {
            get {
                return ResourceManager.GetString("MainForm_HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (Ctrl+F)....
        /// </summary>
        public static string MainForm_SearchButton {
            get {
                return ResourceManager.GetString("MainForm_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search.
        /// </summary>
        public static string MainForm_SearchMenu {
            get {
                return ResourceManager.GetString("MainForm_SearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search....
        /// </summary>
        public static string MainForm_SearchSearchMenu {
            get {
                return ResourceManager.GetString("MainForm_SearchSearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        public static string MainForm_WindowMenu {
            get {
                return ResourceManager.GetString("MainForm_WindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates are available..
        /// </summary>
        public static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Advanced.
        /// </summary>
        public static string SearchForm_Advanced {
            get {
                return ResourceManager.GetString("SearchForm_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Directory:.
        /// </summary>
        public static string SearchForm_Directory {
            get {
                return ResourceManager.GetString("SearchForm_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Excluding File Masks:.
        /// </summary>
        public static string SearchForm_ExcludingFileMask {
            get {
                return ResourceManager.GetString("SearchForm_ExcludingFileMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets:.
        /// </summary>
        public static string SearchForm_ExcludingTargets {
            get {
                return ResourceManager.GetString("SearchForm_ExcludingTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File _Masks: Can be used multiple file masks by seperating with &apos;;&apos;.
        /// </summary>
        public static string SearchForm_FileMask {
            get {
                return ResourceManager.GetString("SearchForm_FileMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Si_ze Range:.
        /// </summary>
        public static string SearchForm_FileSizeRange {
            get {
                return ResourceManager.GetString("SearchForm_FileSizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ignore Case.
        /// </summary>
        public static string SearchForm_IgnoreCase {
            get {
                return ResourceManager.GetString("SearchForm_IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include _Subdirectories.
        /// </summary>
        public static string SearchForm_IncludeSubdirectories {
            get {
                return ResourceManager.GetString("SearchForm_IncludeSubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max:.
        /// </summary>
        public static string SearchForm_Max {
            get {
                return ResourceManager.GetString("SearchForm_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min:.
        /// </summary>
        public static string SearchForm_Min {
            get {
                return ResourceManager.GetString("SearchForm_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string SearchForm_Open {
            get {
                return ResourceManager.GetString("SearchForm_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Regular Expression.
        /// </summary>
        public static string SearchForm_RegularExpression {
            get {
                return ResourceManager.GetString("SearchForm_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search _Word: Find files when empty.
        /// </summary>
        public static string SearchForm_SearchWord {
            get {
                return ResourceManager.GetString("SearchForm_SearchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Conditions.
        /// </summary>
        public static string SearchForm_Title {
            get {
                return ResourceManager.GetString("SearchForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
    }
}
