//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekome.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nekome.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Abort.
        /// </summary>
        public static string MainForm_AbortMenu {
            get {
                return ResourceManager.GetString("MainForm_AbortMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string MainForm_AboutMenu {
            get {
                return ResourceManager.GetString("MainForm_AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Check Updates....
        /// </summary>
        public static string MainForm_CheckUpdateMenu {
            get {
                return ResourceManager.GetString("MainForm_CheckUpdateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check _Updates On Start Up.
        /// </summary>
        public static string MainForm_CheckUpdateOnStartUpMenu {
            get {
                return ResourceManager.GetString("MainForm_CheckUpdateOnStartUpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close Tab.
        /// </summary>
        public static string MainForm_CloseTabMenu {
            get {
                return ResourceManager.GetString("MainForm_CloseTabMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Find Tools....
        /// </summary>
        public static string MainForm_EditFindToolsButton {
            get {
                return ResourceManager.GetString("MainForm_EditFindToolsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit _Search Tools....
        /// </summary>
        public static string MainForm_EditFindToolsMenu {
            get {
                return ResourceManager.GetString("MainForm_EditFindToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Grep Tools....
        /// </summary>
        public static string MainForm_EditGrepToolsButton {
            get {
                return ResourceManager.GetString("MainForm_EditGrepToolsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit _Grep Tools....
        /// </summary>
        public static string MainForm_EditGrepToolsMenu {
            get {
                return ResourceManager.GetString("MainForm_EditGrepToolsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MainForm_ExitMenu {
            get {
                return ResourceManager.GetString("MainForm_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainForm_FileMenu {
            get {
                return ResourceManager.GetString("MainForm_FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MainForm_HelpMenu {
            get {
                return ResourceManager.GetString("MainForm_HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (Ctrl+F)....
        /// </summary>
        public static string MainForm_SearchButton {
            get {
                return ResourceManager.GetString("MainForm_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search.
        /// </summary>
        public static string MainForm_SearchMenu {
            get {
                return ResourceManager.GetString("MainForm_SearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search....
        /// </summary>
        public static string MainForm_SearchSearchMenu {
            get {
                return ResourceManager.GetString("MainForm_SearchSearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        public static string MainForm_WindowMenu {
            get {
                return ResourceManager.GetString("MainForm_WindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Advanced.
        /// </summary>
        public static string SearchForm_Advanced {
            get {
                return ResourceManager.GetString("SearchForm_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Directory:.
        /// </summary>
        public static string SearchForm_Directory {
            get {
                return ResourceManager.GetString("SearchForm_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Excluding File Masks:.
        /// </summary>
        public static string SearchForm_ExcludingFileMask {
            get {
                return ResourceManager.GetString("SearchForm_ExcludingFileMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets:.
        /// </summary>
        public static string SearchForm_ExcludingTargets {
            get {
                return ResourceManager.GetString("SearchForm_ExcludingTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File _Masks: Can be used multiple file masks by seperating with &apos;;&apos;.
        /// </summary>
        public static string SearchForm_FileMask {
            get {
                return ResourceManager.GetString("SearchForm_FileMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Si_ze Range:.
        /// </summary>
        public static string SearchForm_FileSizeRange {
            get {
                return ResourceManager.GetString("SearchForm_FileSizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ignore Case.
        /// </summary>
        public static string SearchForm_IgnoreCase {
            get {
                return ResourceManager.GetString("SearchForm_IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include _Subdirectories.
        /// </summary>
        public static string SearchForm_IncludeSubdirectories {
            get {
                return ResourceManager.GetString("SearchForm_IncludeSubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max:.
        /// </summary>
        public static string SearchForm_Max {
            get {
                return ResourceManager.GetString("SearchForm_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min:.
        /// </summary>
        public static string SearchForm_Min {
            get {
                return ResourceManager.GetString("SearchForm_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string SearchForm_Open {
            get {
                return ResourceManager.GetString("SearchForm_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Regular Expression.
        /// </summary>
        public static string SearchForm_RegularExpression {
            get {
                return ResourceManager.GetString("SearchForm_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search _Word: Find files when empty.
        /// </summary>
        public static string SearchForm_SearchWord {
            get {
                return ResourceManager.GetString("SearchForm_SearchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Conditions.
        /// </summary>
        public static string SearchForm_Title {
            get {
                return ResourceManager.GetString("SearchForm_Title", resourceCulture);
            }
        }
    }
}
