//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GFV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check updates.
        ///{0}.
        /// </summary>
        public static string AutoUpdate_FailedToCheckUpdates {
            get {
                return ResourceManager.GetString("AutoUpdate_FailedToCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download installer.
        ///{0}.
        /// </summary>
        public static string AutoUpdate_FailedToDownloadInstaller {
            get {
                return ResourceManager.GetString("AutoUpdate_FailedToDownloadInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is found. Do you install this?.
        /// </summary>
        public static string AutoUpdate_FoundMessage {
            get {
                return ResourceManager.GetString("AutoUpdate_FoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available..
        /// </summary>
        public static string AutoUpdate_NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("AutoUpdate_NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update.
        /// </summary>
        public static string AutoUpdate_Title {
            get {
                return ResourceManager.GetString("AutoUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Additional File Types:.
        /// </summary>
        public static string SettingsDialog_AdditionalFileTypes {
            get {
                return ResourceManager.GetString("SettingsDialog_AdditionalFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each extension is separated with &apos;;&apos;..
        /// </summary>
        public static string SettingsDialog_AdditionalFileTypesDescription {
            get {
                return ResourceManager.GetString("SettingsDialog_AdditionalFileTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        public static string SettingsDialog_AdditionaryFileTypesExtensionsColumn {
            get {
                return ResourceManager.GetString("SettingsDialog_AdditionaryFileTypesExtensionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SettingsDialog_AdditionaryFileTypesNameColumn {
            get {
                return ResourceManager.GetString("SettingsDialog_AdditionaryFileTypesNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string SettingsDialog_FileTab {
            get {
                return ResourceManager.GetString("SettingsDialog_FileTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use _glass background..
        /// </summary>
        public static string SettingsDialog_GlassBackground {
            get {
                return ResourceManager.GetString("SettingsDialog_GlassBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide inactive windows from Alt+Tab..
        /// </summary>
        public static string SettingsDialog_HideFromAltTab {
            get {
                return ResourceManager.GetString("SettingsDialog_HideFromAltTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide inactive windows from taskbar..
        /// </summary>
        public static string SettingsDialog_HideFromTaskbar {
            get {
                return ResourceManager.GetString("SettingsDialog_HideFromTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Primary:.
        /// </summary>
        public static string SettingsDialog_PrimarySortOrder {
            get {
                return ResourceManager.GetString("SettingsDialog_PrimarySortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Secondary:.
        /// </summary>
        public static string SettingsDialog_SecondarySortOrder {
            get {
                return ResourceManager.GetString("SettingsDialog_SecondarySortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order:.
        /// </summary>
        public static string SettingsDialog_SortOrder {
            get {
                return ResourceManager.GetString("SettingsDialog_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string SettingsDialog_SortOrderDescending {
            get {
                return ResourceManager.GetString("SettingsDialog_SortOrderDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsDialog_Title {
            get {
                return ResourceManager.GetString("SettingsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string SettingsDialog_ViewTab {
            get {
                return ResourceManager.GetString("SettingsDialog_ViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string ViewerWindow_AboutMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Auto Image Size.
        /// </summary>
        public static string ViewerWindow_AutoImageSizeMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_AutoImageSizeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _None.
        /// </summary>
        public static string ViewerWindow_AutoImageSizeNoneMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_AutoImageSizeNoneMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_ell.
        /// </summary>
        public static string ViewerWindow_BellMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_BellMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Bilinear.
        /// </summary>
        public static string ViewerWindow_BilinearMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_BilinearMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_Spline.
        /// </summary>
        public static string ViewerWindow_BSplineMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_BSplineMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cascade.
        /// </summary>
        public static string ViewerWindow_CascadeMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_CascadeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check _Updates....
        /// </summary>
        public static string ViewerWindow_CheckUpdatesMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_CheckUpdatesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Check Updates On Startup.
        /// </summary>
        public static string ViewerWindow_CheckUpdatesOnStartupMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_CheckUpdatesOnStartupMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close Window.
        /// </summary>
        public static string ViewerWindow_CloseMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_CloseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string ViewerWindow_ExitMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string ViewerWindow_FileMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to window h_eight, large only.
        /// </summary>
        public static string ViewerWindow_FitToHeightLargeOnlyMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToHeightLargeOnlyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to window _height.
        /// </summary>
        public static string ViewerWindow_FitToHeightMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToHeightMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to _longer edge.
        /// </summary>
        public static string ViewerWindow_FitToLongerEdge {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToLongerEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to lo_nger edge, large only.
        /// </summary>
        public static string ViewerWindow_FitToLongerEdgeLargeOnly {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToLongerEdgeLargeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to _shorter edge.
        /// </summary>
        public static string ViewerWindow_FitToShorterEdge {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToShorterEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to sh_orter edge, large only.
        /// </summary>
        public static string ViewerWindow_FitToShorterEdgeLargeOnly {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToShorterEdgeLargeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to window wid_th, large only.
        /// </summary>
        public static string ViewerWindow_FitToWidthLargeOnlyMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToWidthLargeOnlyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to window wi_dth.
        /// </summary>
        public static string ViewerWindow_FitToWidthMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToWidthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to w_indow, large only.
        /// </summary>
        public static string ViewerWindow_FitToWindowLargeOnlyMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToWindowLargeOnlyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to _window.
        /// </summary>
        public static string ViewerWindow_FitToWindowMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Gaussian.
        /// </summary>
        public static string ViewerWindow_GaussianMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_GaussianMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string ViewerWindow_HelpMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hermite.
        /// </summary>
        public static string ViewerWindow_HermiteMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_HermiteMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lanczos.
        /// </summary>
        public static string ViewerWindow_LanczosMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_LanczosMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mitshell.
        /// </summary>
        public static string ViewerWindow_MitshellMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_MitshellMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next File.
        /// </summary>
        public static string ViewerWindow_NextFileMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_NextFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next Page.
        /// </summary>
        public static string ViewerWindow_NextPageMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_NextPageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op_en In New Window....
        /// </summary>
        public static string ViewerWindow_OpenInNewWindowMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_OpenInNewWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string ViewerWindow_OpenMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  _New Window.
        /// </summary>
        public static string ViewerWindow_OpenNewWindowMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_OpenNewWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Previous File.
        /// </summary>
        public static string ViewerWindow_PreviousFileMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_PreviousFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Previous Page.
        /// </summary>
        public static string ViewerWindow_PreviousPageMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_PreviousPageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quick.
        /// </summary>
        public static string ViewerWindow_QuickMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_QuickMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Recent Files.
        /// </summary>
        public static string ViewerWindow_RecentFilesMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_RecentFilesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Resize Method.
        /// </summary>
        public static string ViewerWindow_ResizeMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ResizeMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Scale.
        /// </summary>
        public static string ViewerWindow_ScaleMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ScaleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se_ttings....
        /// </summary>
        public static string ViewerWindow_SettingsMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _Menubar.
        /// </summary>
        public static string ViewerWindow_ShowMenubarMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ShowMenubarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stack Horizontal.
        /// </summary>
        public static string ViewerWindow_StackHorizontalMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_StackHorizontalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack V_ertical.
        /// </summary>
        public static string ViewerWindow_StackVerticalMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_StackVerticalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tile  Horizontal.
        /// </summary>
        public static string ViewerWindow_TileHorizontalMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_TileHorizontalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile _Vertical.
        /// </summary>
        public static string ViewerWindow_TileVerticalMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_TileVerticalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string ViewerWindow_ViewMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        public static string ViewerWindow_WindowMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_WindowMenu", resourceCulture);
            }
        }
    }
}
