//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.235
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFV.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GFV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Failed to check updates.
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoUpdate_FailedToCheckUpdates {
            get {
                return ResourceManager.GetString("AutoUpdate_FailedToCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to download installer.
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoUpdate_FailedToDownloadInstaller {
            get {
                return ResourceManager.GetString("AutoUpdate_FailedToDownloadInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version {0} is found. Do you install this? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoUpdate_FoundMessage {
            get {
                return ResourceManager.GetString("AutoUpdate_FoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No updates available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoUpdate_NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("AutoUpdate_NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AutoUpdate_Title {
            get {
                return ResourceManager.GetString("AutoUpdate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_AboutMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Auto Image Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_AutoImageSizeMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_AutoImageSizeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_AutoImageSizeNoneMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_AutoImageSizeNoneMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B_ell に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_BellMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_BellMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Bilinear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_BilinearMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_BilinearMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B_Spline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_BSplineMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_BSplineMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Cascade に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_CascadeMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_CascadeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check _Updates... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_CheckUpdatesMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_CheckUpdatesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Check Updates On Startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_CheckUpdatesOnStartupMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_CheckUpdatesOnStartupMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_CloseMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_CloseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_ExitMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_FileMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit to window h_eight, large only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_FitToHeightLargeOnlyMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToHeightLargeOnlyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit to window _height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_FitToHeightMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToHeightMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit to _longer edge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_FitToLongerEdge {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToLongerEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit to lo_nger edge, large only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_FitToLongerEdgeLargeOnly {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToLongerEdgeLargeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit to _shorter edge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_FitToShorterEdge {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToShorterEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit to sh_orter edge, large only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_FitToShorterEdgeLargeOnly {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToShorterEdgeLargeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit to window wid_th, large only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_FitToWidthLargeOnlyMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToWidthLargeOnlyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit to window wi_dth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_FitToWidthMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToWidthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit to w_indow, large only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_FitToWindowLargeOnlyMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToWindowLargeOnlyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit to _window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_FitToWindowMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Gaussian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_GaussianMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_GaussianMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_HelpMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Hermite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_HermiteMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_HermiteMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Lanczos に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_LanczosMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_LanczosMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Mitshell に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_MitshellMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_MitshellMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Next File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_NextFileMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_NextFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Op_en In New Window... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_OpenInNewWindowMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_OpenInNewWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_OpenMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///    _New Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_OpenNewWindowMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_OpenNewWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Previous File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_PreviousFileMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_PreviousFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Quick に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_QuickMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_QuickMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Recent Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_RecentFilesMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_RecentFilesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Resize Method に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_ResizeMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ResizeMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_ScaleMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ScaleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show _Menubar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_ShowMenubarMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ShowMenubarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Stack Horizontal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_StackHorizontalMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_StackHorizontalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stack V_ertical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_StackVerticalMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_StackVerticalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Tile  Horizontal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_TileHorizontalMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_TileHorizontalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tile _Vertical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_TileVerticalMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_TileVerticalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_ViewMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewerWindow_WindowMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_WindowMenu", resourceCulture);
            }
        }
    }
}
