//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GFV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string ViewerWindow_AboutMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Auto Image Size.
        /// </summary>
        public static string ViewerWindow_AutoImageSizeMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_AutoImageSizeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _None.
        /// </summary>
        public static string ViewerWindow_AutoImageSizeNoneMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_AutoImageSizeNoneMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_ell.
        /// </summary>
        public static string ViewerWindow_BellMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_BellMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Bilinear.
        /// </summary>
        public static string ViewerWindow_BilinearMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_BilinearMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_Spline.
        /// </summary>
        public static string ViewerWindow_BSplineMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_BSplineMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string ViewerWindow_CloseMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_CloseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string ViewerWindow_ExitMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string ViewerWindow_FileMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to window h_eight, large only.
        /// </summary>
        public static string ViewerWindow_FitToHeightLargeOnlyMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToHeightLargeOnlyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to window _height.
        /// </summary>
        public static string ViewerWindow_FitToHeightMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToHeightMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to window wid_th, large only.
        /// </summary>
        public static string ViewerWindow_FitToWidthLargeOnlyMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToWidthLargeOnlyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to window wi_dth.
        /// </summary>
        public static string ViewerWindow_FitToWidthMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToWidthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to w_indow, large only.
        /// </summary>
        public static string ViewerWindow_FitToWindowLargeOnlyMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToWindowLargeOnlyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to _window.
        /// </summary>
        public static string ViewerWindow_FitToWindowMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_FitToWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Gaussian.
        /// </summary>
        public static string ViewerWindow_GaussianMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_GaussianMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string ViewerWindow_HelpMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hermite.
        /// </summary>
        public static string ViewerWindow_HermiteMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_HermiteMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lanczos.
        /// </summary>
        public static string ViewerWindow_LanczosMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_LanczosMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Mitshell.
        /// </summary>
        public static string ViewerWindow_MitshellMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_MitshellMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string ViewerWindow_OpenMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quick.
        /// </summary>
        public static string ViewerWindow_QuickMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_QuickMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Resize Method.
        /// </summary>
        public static string ViewerWindow_ResizeMethodMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ResizeMethodMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string ViewerWindow_ViewMenu {
            get {
                return ResourceManager.GetString("ViewerWindow_ViewMenu", resourceCulture);
            }
        }
    }
}
